#include <stdio.h>
#include <stdlib.h>
#include <SDL/SDL.h>
#include <fmod/fmod.h>
#include <fmod/fmod_common.h>
#include <fmod/fmod_errors.h>

/*
                                                    JOUER DU SON AVEC FMOD
I./ INITIALISER ET LIBERER UN OBJET SYSTEME
1.) INCLURE LE header

#include <fmod/fmod.h>
ET J'AI MOI-MEME RAJOUTE (car je l'ai vu quelque part):
#include <fmod/fmod_errors.h>
#include <fmod/fmod_common.h>

2.) CREER ET INITIALISER UN OBJET SYSTEME

UN OBJET SYSTEME EST UNE VARIABLE QUI ME SERVIRA TOUT AU LONG DU PROG A DEFINIR DES PAREMETRES DE LA LIBRAIRIE.
AU LIEU D'INITIALISER EXPLICITEMENT TOUTE LA LIB AVEC UNE FONCTION COMME POUR LA SDL, ON TRAVAILLE AVEC UN OBJET DONT LE ROLE EST
DE DEFINIR LE COMPORTEMENT DE LA LIB.

POUR CREER UN OBJET SYSTEME, IL SUFFIT DE DECLARER UN POINTEUR SUR LE TYPE FMOD_SYSTEM. PAR EXEMPLE:
FMOD_SYSTEM *system;

POUR ALLOUER DANS LA MEMOIRE CET OBJET SYSTEME, ON UTILISE LA FONCTION FMOD_System_Create DONT VOICI LE PROTOTYPE:
FMOD_RESULT FMOD_System_Create(
    FMOD_SYSTEM **system
    );
NOTE : CETTE FCT PREND POUR PARAMETRE UN POINTEUR SUR UN POINTEUR DE FMOD_SYSTEM. system N'AYANT PAS ETE ALLOUE PAR malloc()
OU UNE AUTRE FONCTION, LA FONCTION FMOD_System_Create PREND UN TEL PARAMETRE POUR, ENTRE AUTRES, ALLOUER LE POINTEUR system.
CONCRETEMENT, APRES AVOIR DECLARE UN OBJET SYSTEME, IL SUFFIT DE FAIRE :
FMOD_System_Create(&system);
VOILA, ON DISPOSE MAINTENANT D'UN OBJET SYSTEM ALLOUE EN MEMOIRE. IL NE RESTE PLUS QU'A L'INITIALISER COMME CECI :
PROTO:
FMOD_RESULT FMOD_System_Init(
FMOD_System *system,
int maxchannels,
FMOD_INITFLAGS flags,
void* extradriverdata
);
LA FONCTION PREND DONC 4 PARAMETRES :
    -   LE POINTEUR QUE JE VEUX INITIALISER
    -   LE PARAMETRE maxchannels EST LE NB MAXIMUM DE CANAUX QUE DEVRA GERER FMOD. EN D'AUTRES TERMES, C'EST LE NB MAXIMUM DE SONS
    QUI POURRONT ETRE JOUES EN MEME TEMPS. TOUT DEPEND DE LA PUISSANCE DE MA CARTE SON. ON CONSEILLE GENERALEMENT UNE VALEUR DE
    32 (CE SERA SUFFISANT POUR LA PLUPART DES PETITS JEUX). POUR INFO, FMOD PEUT GERER JUSQU'A 1024 CANAUX DIFFERENTS.
    -   LE PAREMETRE flag NE M'INTERESSERA PAS TELLEMENT DANS CE COURS. JE LUI DONNERAIS DONC LA VALEUR FMOD_INIT_NORMAL
    -   ININT ==> NULL

DONC, POUR INITIALISER JE FERAIS COMME SUIT :
FMOD_System_Init(system, 2, FMOD_INIT_NORMAL, NULL);

MAINTENANT JE DISPOSE D'UN OBJET SYSTEM PRET A L'EMPLOI

3.) FERMER ET LIBERER UN OBJET SYSTEME

ON FERME, PUIS ON LIBERE UN OBJET SYSTEME AVEC LES DEUX FONCTIONS SUIVANTES :

FMOD_System_Close(system);
FMOD_System_Release(system);

II./ LES SONS COURTS

TAPER free sounds DANS google. OU BIEN :
UN BON SITE POUR TROUVER DES SONS COURTS : findsounds.com

1.) LES ETAPES A SUIVRE POUR JOUER UN SON

i./ JE CHARGE EN MEMOIRE LES SONS QUE JE VEUX JOUER DES LE DEBUT DU PROG
ii./ JE JOUE LE SON
iii./ JE LIBERE TOUS LES SONS A LA FIN DU PROG

2.) LE POINTEUR

PREMIERE ETAPE : CREER UN POINTEUR DE TYPE FMOD_SOUND QUI REPRESENTERA MON SON :
FMOD_SOUND *tir = NULL;

3.) CHARGER LE SON

DEUXIEME ETAPE : CHARGER LE SON AVEC LA FONCTION FMOD_System_CreateSound. CELLE-CI PREND 5 PARAMETRES :

    -   UN OBJET SYSTEME (QUI DOIT ETRE DEJA PRET A L'EMPLOI)
    -   LE NOM DU FICHIER SON A CHARGER. IL PEUT ETRE AU FORMAT WAV, MP3, OGG, etc. TOUTEFOIS, IL VAUT MIEUX CHARGER DES SONS
        COURTS. EN EFFET, LA FCT CHARGERA ET DECODERA LE SON EN MEMOIRE, CE QUI PRENDRA DE LA PLACE SI LE SON EST UNE MUSIQUE.
    -   LE TROISIEME PARAMETRE EST UN flag. CELUI-CI EST PARTICULIEREMENT IMPORTANT, CAR C'EST GRACE A LUI QUE JE DIS A FMOD
        QUE LE SON QUE JE VEUX JOUER EST UN SON COURT. POUR CECI, J'UTILISERAI LA VALEUR FMOD_CREATESAMPLE
    -   ININT ==> NULL / 0
    -   LE DERNIER PARAMETRE EST DE TYPE FMOD_SOUND **sound ET C'EST CE POINTEUR-LA QUE J'UTILISERAI PAR LA SUITE POUR JOUER
        MON SON

VOICI UN EXEMPLE DE CHARGEMENT :
FMOD_System_CreateSound(system, "tir.wav", FMOD_CREATESAMPLE, 0, &tir);

ICI, LE POINTEUR tir FAIT REFERENCE A CE SON PAR LA SUITE DU PROG
SI TOUT SE PASSE BIEN, LA FCT RENVOIE LA VALEUR FMOD_OK DE TYPE FMOD_RESULT, D'OU LA NECESSITE DE CREER LA VARIABLE SUIVANTE
AU PREALABLE :
FMOD_RESULT resultat; ==> POUR TESTER S'IL Y A EU UN PROBLEME LORS DE L'OUVERTUR DU FICHIER AUDIO

4.) JOUER LE SON
a./ RECUPERER UN CANAL OU UN GROUPE DE CANAUX

ATTENTION, IL FAUDRA AU PREALABLE CREER UN CANAL COMME CECI :
FMOD_CHANNEL *channel;

ENSUITE, IL FAUT RECUPERER LE CANAL A PARTIR D'UN NUMERO ID AVEC LA FONCTION FMOD_System_GetChannel.
PAR EXEMPLE, SI J'AI UN OBJET SYSTEME system ET QUE JE VEUX RECUPERER LE CANAL N°9, IL FAUT FAIRE COMME CECI :
FMOD_System_GetChannel(system, 9, &channel);
AINSI, J'AI ATTRIBUE LE CANAL 9 A MON CANAL channel.
DONC 3 PARAMETRES :
    -   L'OBJET SYSTEME
    -   LE NUMERO ID DU CANAL
    -   L'ADRESSE DU POINTEUR OU L'ON VEUT STOCKER L'INFORMATION

ON PEUT AUSSI RECUPERER TOUT UN GROUPE DE CANAUX EN UN SEUL POINTEUR; CELA EVITE DE REFAIRE LA MEME MANIPULATION POUR CHAQUE CANAL
DISTINCT. LE TYPE D'UN GROUPE DE CANAUX EST FMOD_CHANNELGROUP. DONC JE FAIS :
FMOD_CHANNELGROUP *canaux;
ET LA FONCTION QUI PERMET D'OBTENIR UN POINTEUR VERS LA TOTALITE DES CANAUX UTILISES PAR UN OBJET SYSTEME EST LA SUIVANTE:
FMOD_System_GetMasterChannelGroup
LE MODE DE FONCTIONNEMENT EST QUASIMENT IDENTIQUE A FMOD_System_GetChannel A CECI PRES :
IL N'Y A PAS LE PARAMETRE NUMERO ID DU CANAL (QUE DEUX PARAMETRES DONC).

ET ENFIN, POUR JOUER LE SON, J'APPELLE LA FONCTION FMOD_System_PlaySound QUI PRENDRA 5 PARAMETRES :

    -   L'OBJET SYSTEME
    -   LE POINTEUR SUR LE SON
    -   ININT ==> NULL ou 0
    -   ININT ==> NULL ou 0
    -   UN DERNIER PARAMETRE DE TYPE FMOD_CHANNEL **channel POUR LE NUMERO DE CANAL SUR LEQUEL JOUER
AINSI, EXEMPLE :
FMOD_System_PlaySound(system, tir, 0, 0, &channel);

5.) LIBERER LE SON DE LA MEMOIRE

LORSQUE JE N'AI PLUS BESOIN DU SON, JE DOIS LE LIBERER DE LA MEMOIRE COMME CECI :
FMOD_Sound_Release(tir);

III./ LES MUSIQUES (MP3, OGG, WMA...)

EN THEORIE, LE FLAG FMOD_CREATESAMPLE PERMET DE CHARGER N'IMPORTE QUEL TYPE DE SON, Y COMPRIS LES FORMATS COMPRESSES MP3, OGG,
WMA. LE PROBLEME CONCERNE LES SONS LONGS, I.E. LES MUSIQUES. EN EFFET, CELLES-CI DURENT 3-4 MINUTES. OR AVEC CE FLAG,
FMOD_System_CreateSound CHARGE TOUT LE FICHIER EN MEMOIRE (ET C'EST LA VERSION DECOMPRESSEE QUI EST MISE EN MEMOIRE, DONC CELA
PREND BCP DE PLACE).
SI J'AI UN SON LONG, IL EST PREFERABLE DE LE CHARGER EN streaming, I.E. D'EN CHARGER DE PETITS BOUTS AU FUR ET A MESURE DE LA
LECTURE. C'EST D'AILLEURS CE QUE FONT TOUS LES LECTEURS AUDIO.

1.) TROUVER DES MUSIQUES

ATTENTION, TERRAIN MINE. AVEC TOUT CE QUI EST DROIT D'AUTEUR ET TRALALA.
HEUREUSEMENT, IL Y A LES MUSIQUES LIBRES DE DROIT ==> LES AUTEURS M'AUTORISENT A DIFFUSER LIBREMENT LEURS CHANSONS (DU MOMENT QUE
JE N'EN TIRE AUCUN PROFIT).
BON SITE : jamendo.com

2.) LES ETAPES A SUIVRE POUR JOUER UNE MUSIQUE

LA SEULE DIFFERENCE EST LE FLAG DONNE A LA FONCTION FMOD_System_CreateSound. AU LIEU DE LUI DONNER LE FLAG FMOD_CREATESAMPLE,
JE LUI DONNERAI LES FLAGS SUIVANTS : FMOD_2D | FMOD_CREATESTREAM.
C'EST FMOD_CREATESTREAM QUI DIRA AU FMOD DE CHARGER LA MUSIQUE BOUT PAR BOUT.

3.) MODIFIER LE VOLUME

ON PEUT MODIFIER LE VOLUME SOIT POUR UN CANAL PRECIS, SOIT POUR TOUS LES CANAUX. PAR EXEMPLE, POUR LE FAIRE POUR TOUS LES CANAUX,
IL FAUT D'ABORD RECUPERER UN POINTEUR VERS LE GROUPE DE CANAUX, PUIS UTILISER LA FCT FMOD_ChannelGroup_SetVolume DONT LE PROTO:
FMOD_RESULT FMOD_ChannelGroup_SetVolume(
FMOD_CHANNELGROUP* channelgroup,
float volume
);
LE PARAMETRE volume EST DU TYPE float, TEL QUE 0.0 CORRESPOND AU SILENCE, ET 1.0 A UNE LECTURE PLEINE PUISSANCE (C'EST CETTE
VALEUR QUI EST PAR DEFAUT).

ATTENTION, CETTE FCT N'A PAS MARCHE QUAND JE L'AI PLACEE AVANT LA BOUCLE PRINCIPALE (A PLACER DANS LA BOUCLE DONC).

4.) REPETITION DE LA CHANSON

FCT : FMOD_Sound_SetLoopCount QUI PREND DEUX PARAMETRES :
    -   LE POINTEUR VERS LA CHANSON
    -   LE NB DE FOIS QU'ELLE DOIT ETRE REPETEE. 1 ==> CHANSON REPETEE DEUX FOIS. NB NEGATIF ==> CHANSON REPETEE A L'INFINI.
AVEC CE CODE SOURCE, MA MUSIQUE SERA REPETEE A L'INFINI :
FMOD_Sound_SetLoopCount(musique, -1);
CETTE FOIS, J'APPELLE LA FCT AVANT LA BOUCLE PRINCIPALE
ATTENTION : POUR QUE LA REPETITION FONCTIONNE IL FAUT ENVOYER FMOD_LOOP_NORMAL EN TROISIEME PAREMETRE DE LA FCT
FMOD_System_CreateSound.

5.) METTRE EN PAUSE LA CHANSON

IL Y A ICI 2 FONCTIONS A CONNAITRE :
    -   FMOD_Channel_GetPaused(canal, &etat) : INDIQUE SI LA CHANSON JOUEE SUR LE CANAL INDIQUEE EST EN PAUSE OU PAS. ELLE MET
    VRAI DANS etat SI LA CHANSON EST EN PAUSE, FAUX SI ELLE EST EN TRAIN D'ETRE JOUEE.
    -   FMOD_Channel_SetPaused(canal, etat) : MET EN PAUSE OU REACTIVE LA LECTURE DE LA CHANSON SUR LE CANAL INDIQUEE. IL FAUDRA
    ENVOYER 1 (VRAI) POUR METTRE LA CHANSON EN PAUSE, ET 0 (FAUX) POUR REACTIVER LA LECTURE.
CE BOUT DE CODE DE FENETRE SDL MET EN PAUSE LA CHANSON SI ON APPUIE SUR LA TOUCHE p DU CLAVIER, ET LA REACTIVE SI ON APPUIE DE
NOUVEAU SUR p.
case KEYDOWN:
    if(event.key.keysym.sym == SDLK_p)
    {
        FMOD_BOOL etat;
        FMOD_Channel_GetPaused(canal, &etat);
        if(etat == 1)
            FMOD_Channel_SetPaused(canal, 0);
        else
            FMOD_Channel_SetPaused(canal, 1);
    }
    break;

SI ON VEUT APPLIQUER LE MEME TRAITEMENT A TOUS LES CANAUX REUNIS, IL FAUDRA PASSER PAR LES FCTS :
FMOD_ChannelGroup_GetPaused ET FMOD_ChannelGroup_SetPaused A LA SEULLE DIFFERENCE QU'IL FAUDRA METTRE EN PARAMETRE un
FMOD_CHANNELGROUP AU LIEU D'UN FMOD_CHANNEL.

6.) STOPPER LA LECTURE

IL SUFFIT D'APPELER FMOD_Channel_Stop POUR STOPPER LA MUSIQUE SUR UN CANAL, COMME CECI :
FMOD_Channel_Stop(channel);
.. OU BIEN FMOD_ChannelGroup_Stop POUR UN ENSEMBLE DE CANAUX, EN ENVOYANT LE POINTEUR VERS LE GROUPE DE CANAUX.
ATTENTION, FCT A PLACER LA OU ON CHANGE LE PARAMETRE DE LA BOUCLE PRINCIPALE (continuer = 0).


POUR FINIR, NE PAS OUBLIER DE LIBERER LA MUSIQUE DE LA MEMOIRE A LA FIN ==> COMME POUR LES SONS COURTS!

*/
int main(int argc, char *argv[])
{
    SDL_Surface *ecran = NULL, *viseur = NULL;
    SDL_Event event;
    SDL_Rect position;
    int continuer = 1;
    FMOD_SYSTEM *system;
    FMOD_SOUND *tir = NULL, *musique = NULL;

    FMOD_RESULT resultat, resultat2;

    //CREATION ET INITIALISATION D'UN OBJET SYSTEME:
    FMOD_System_Create(&system);
    FMOD_System_Init(system, 2, FMOD_INIT_NORMAL, NULL);
    // CHARGEMENT DU SON ET VERIFICATION DU CHARGEMENT
    resultat = FMOD_System_CreateSound(system, "shot.wav", FMOD_CREATESAMPLE, 0, &tir);
    if(resultat != FMOD_OK)
    {
        fprintf(stderr, "Impossible de lire shot.wav\n");
        exit(EXIT_FAILURE);
    }
    resultat2 = FMOD_System_CreateSound(system, "wish_you_were_here.mp3", FMOD_2D | FMOD_CREATESTREAM |FMOD_LOOP_NORMAL, 0, &musique);
    if(resultat2 != FMOD_OK)
    {
        fprintf(stderr, "Impossible de lire le morceau");
        exit(EXIT_FAILURE);
    }
    FMOD_CHANNEL *channel, *musicChannel;
    FMOD_System_GetChannel(system, 9, &channel);
    FMOD_System_GetChannel(system, 8, &musicChannel);
    /* POUR RECUPERER TOUT UN GROUPE DE CANAUX EN UN SEUL POINTEUR :
    FMOD_CHANNELGROUP *canaux;
    FMOD_System_GetMasterChannelGroup(system, &canaux);
    */
    float volume = 0.7;

    FMOD_System_PlaySound(system, musique, 0, 0, &musicChannel);
    FMOD_Sound_SetLoopCount(musique, -1);
    FMOD_Channel_SetLoopCount(musicChannel, 0); // FCT A PRIVILEGIER


    SDL_Init(SDL_INIT_VIDEO);
    ecran = SDL_SetVideoMode(800, 600, 32, SDL_HWSURFACE);
    SDL_WM_SetCaption("Jouer du son avec FMOD", NULL);
    viseur = SDL_LoadBMP("viseur.bmp");
    SDL_ShowCursor(SDL_DISABLE);

    while(continuer)
    {
        SDL_WaitEvent(&event);
        FMOD_Channel_SetVolume(musicChannel, volume); // MARCHE PAS SI PLACEE AVANT LA BOUCLE
        switch(event.type)
        {
            case SDL_QUIT:
                continuer = 0;
                FMOD_Channel_Stop(channel);
                FMOD_Channel_Stop(musicChannel);
                break;
            case SDL_MOUSEBUTTONDOWN:
                if(event.button.button == SDL_BUTTON_LEFT)
                    FMOD_System_PlaySound(system, tir, 0, 0, &channel);
                break;
            case SDL_MOUSEMOTION:
                position.x = event.motion.x - viseur->w / 2;
                position.y = event.motion.y - viseur->h / 2;
                break;
            case SDL_KEYDOWN:
                if(event.key.keysym.sym == SDLK_p)// SI ON APPUIE SUR P
                {
                    FMOD_BOOL etat;
                    FMOD_Channel_GetPaused(musicChannel, &etat); // etat ==> 1 SI EN PAUSE; etat ==> 0 SI EN LECTURE;
                    if(etat == 1) // SI LA CHANSON EST EN PAUSE
                        FMOD_Channel_SetPaused(musicChannel, 0); // ON ENLEVE LA PAUSE
                    else // SINON, ELLE EST EN COURS DE LECTURE
                        FMOD_Channel_SetPaused(musicChannel, 1); // ON MET EN PAUSE
                }
                else if(event.key.keysym.sym == SDLK_SPACE)
                    FMOD_Channel_Stop(musicChannel);
                else if(event.key.keysym.sym == SDLK_j)
                    {
                        FMOD_System_PlaySound(system, musique, 0, 0, &musicChannel);
                    }
                break;
        }
        SDL_FillRect(ecran, NULL, SDL_MapRGB(ecran->format, 0, 0, 0));
        SDL_BlitSurface(viseur, NULL, ecran, &position);
        SDL_Flip(ecran);
    }
    SDL_FreeSurface(viseur);
    SDL_Quit();
    FMOD_Sound_Release(tir);
    FMOD_Sound_Release(musique);
    FMOD_System_Close(system);
    FMOD_System_Release(system);

    return 0;
}
